import type { Room, Booking } from './types';
import { Wifi, Tv, Wind, Utensils, Coffee, BedDouble } from 'lucide-react';

export const rooms: Room[] = [
  {
    id: 'room-101',
    name: 'Luxury King Suite',
    description: 'A luxurious suite with a king-sized bed and a stunning city view. Experience ultimate comfort and elegance.',
    price: 250,
    imageUrl: 'https://picsum.photos/seed/101/600/400',
    imageHint: 'luxury suite',
    amenities: [
      { name: 'WiFi', icon: Wifi },
      { name: 'TV', icon: Tv },
      { name: 'Air Conditioning', icon: Wind },
      { name: 'Room Service', icon: Utensils },
    ],
  },
  {
    id: 'room-102',
    name: 'Cozy Double Room',
    description: 'A cozy room with a double bed, perfect for solo travelers or couples. Modern, clean, and comfortable.',
    price: 150,
    imageUrl: 'https://picsum.photos/seed/102/600/400',
    imageHint: 'double room',
    amenities: [
      { name: 'WiFi', icon: Wifi },
      { name: 'TV', icon: Tv },
      { name: 'Coffee Maker', icon: Coffee },
    ],
  },
  {
    id: 'room-201',
    name: 'Spacious Family Room',
    description: 'A spacious family room with one double bed and two single beds, and amenities for all ages.',
    price: 220,
    imageUrl: 'https://picsum.photos/seed/201/600/400',
    imageHint: 'family room',
    amenities: [
      { name: 'WiFi', icon: Wifi },
      { name: 'TV', icon: Tv },
      { name: 'Air Conditioning', icon: Wind },
      { name: 'Extra Beds', icon: BedDouble },
    ],
  },
  {
    id: 'room-202',
    name: 'Executive Workspace Room',
    description: 'An executive room with a dedicated workspace, ergonomic chair, and high-speed internet.',
    price: 180,
    imageUrl: 'https://picsum.photos/seed/202/600/400',
    imageHint: 'executive room',
    amenities: [
      { name: 'WiFi', icon: Wifi },
      { name: 'TV', icon: Tv },
      { name: 'Air Conditioning', icon: Wind },
      { name: 'Coffee Maker', icon: Coffee },
    ],
  },
  {
    id: 'room-301',
    name: 'Deluxe Garden View',
    description: 'A beautiful deluxe room with a private balcony overlooking the serene hotel gardens. A perfect escape.',
    price: 200,
    imageUrl: 'https://picsum.photos/seed/301/600/400',
    imageHint: 'deluxe room balcony',
    amenities: [
      { name: 'WiFi', icon: Wifi },
      { name: 'TV', icon: Tv },
      { name: 'Air Conditioning', icon: Wind },
      { name: 'Room Service', icon: Utensils },
    ],
  },
  {
    id: 'room-302',
    name: 'Standard Single Room',
    description: 'A standard single room offering comfort, convenience, and value. Ideal for the solo adventurer.',
    price: 120,
    imageUrl: 'https://picsum.photos/seed/302/600/400',
    imageHint: 'single room',
    amenities: [
      { name: 'WiFi', icon: Wifi },
      { name: 'TV', icon: Tv },
    ],
  },
];

export const bookings: Booking[] = [
    {
        id: 'booking-001',
        roomId: 'room-101',
        roomName: 'Luxury King Suite',
        guestName: 'Alice Johnson',
        checkIn: new Date(2024, 7, 1),
        checkOut: new Date(2024, 7, 5),
        status: 'pending',
        totalPrice: 1000,
    },
    {
        id: 'booking-002',
        roomId: 'room-202',
        roomName: 'Executive Workspace Room',
        guestName: 'Bob Williams',
        checkIn: new Date(2024, 7, 3),
        checkOut: new Date(2024, 7, 7),
        status: 'confirmed',
        totalPrice: 720,
    },
    {
        id: 'booking-003',
        roomId: 'room-102',
        roomName: 'Cozy Double Room',
        guestName: 'Charlie Brown',
        checkIn: new Date(2024, 7, 8),
        checkOut: new Date(2024, 7, 10),
        status: 'pending',
        totalPrice: 300,
    },
    {
        id: 'booking-004',
        roomId: 'room-301',
        roomName: 'Deluxe Garden View',
        guestName: 'Diana Prince',
        checkIn: new Date(2024, 7, 12),
        checkOut: new Date(2024, 7, 15),
        status: 'cancelled',
        totalPrice: 600,
    },
    {
        id: 'booking-005',
        roomId: 'room-201',
        roomName: 'Spacious Family Room',
        guestName: 'Eve Adams',
        checkIn: new Date(2024, 7, 15),
        checkOut: new Date(2024, 7, 20),
        status: 'confirmed',
        totalPrice: 1100,
    },
];
